# Trigger build linera-service
name: Build Linera Service

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y build-essential protobuf-compiler libclang-dev llvm-dev pkg-config libssl-dev clang

    - name: Build linera-service
      run: cargo install --locked --root . linera-service@0.14.0

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: linera-service
        path: ./bin/linera-service
